### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ife-adewunmi** [boluwatifeBE/career-map#28]
#### TODO?

- [] Add testing tool and test cases (Cypress or Jest)
- [] GitHub Action (Push and Pull Request, Deploy)
- [] Setup Giscus
- [] Setup Analytics
- [] Setup Guides submission portal
- [] Write Documentation
